### PR TITLE
wip: Remove compress

### PR DESCRIPTION
**Pull request by Pyloons**
Remove compress in load,and change tag compress to block.

### CODE REVIEW

**Comment by marctc** [comment]
Thanks. Nice start. But probably we need to minimize css and js in one file. Maybe we need a gulp task or something similar. Taking a look to wagtail project could give us some clues.

**Comment by marctc** [comment]
And remove all compressor appearences in the code: https://github.com/APSL/puput/search?q=compressor&type=Code&utf8=%E2%9C%93

**Comment by Pyloons** [comment]
How to PR just in this PR...

**Comment by marctc** [comment]
Pushing all the commits to the same branch

**Comment by marctc** [comment]
You can't do this on github. You need to fork the project

**Comment by Pyloons** [comment]
The network environment is terrible and the waiting time is too long. I'm already half past ten here, and I have to work tomorrow, so I'll try to fix it tomorrow night.

**Comment by marctc** [comment]
OK, dont worry!

**Comment by marctc** [comment]
OK, dont worry!

**Pull request closed without merging**
