### PR TITLE
Adding support for Django 2.0 and Wagtail 2.0

### PR DESCRIPTION
**Pull request by MiltonLn**
This PR enables the support for Wagtail 2.0, I've tested almost all the features in a test blog I have and it seemed to be working fine.

For now there's no support for highlighted code blocks for Draftail in this PR but I'm in contact with some of the Wagtail's core devs and they suggested to me to develop that feature as a separated package which could be added to Wagtail's core in the future, so that's my next step and after that I'll be adding that feature here in Pupput.

Also, for now I've added Blockquotes and Code Lines (like this -> `this_is_a_method()`) support for the Puput's Draftail, let me know if there is another Inline or Block feature you want us to support here.

### CODE REVIEW

**Comment by marctc** [comment]
@MiltonLn we need to change the documentation too: https://github.com/APSL/puput/blob/master/docs/setup.rst

**Comment by MiltonLn** [comment]
No, they didn't include it by default, it needs some special code to support those on the Draftail implementation Wagtail did, that didn't sound reasonable to me because I guess a lot of programming blogs use Wagtail, then I talked to Thibaud Colas (the main dev of the Draftail implementation) and he confirmed to me that, then we agreed on developing the feature as a separate package.

**Comment by MiltonLn** [comment]
Oh sure, I'll change the docs too, sorry I missed that, thanks for pointing me that.

**Comment by marctc** [comment]
Check the flake8 issues. I'll check why the tests with Django 2.0 fail. Probably missing migrations.

**Comment by marctc** [comment]
> I talked to Thibaud Colas (the main dev of the Draftail implementation) and he confirmed to me that, then we agreed on developing the feature as a separate package.

Sounds a fantastic idea. Wagtail community definitively will use it.

**Comment by MiltonLn** [comment]
> Check the flake8 issues

Sure.

**Comment by MiltonLn** [comment]
@marctc Updated docs and flake8 stuff

**Comment by Karmak23** [comment]
Hello,

I've been trying to test your branch. After having upgraded the django settings and everything wagtail related, I still get :

```
django.template.exceptions.TemplateSyntaxError: 'wagtailroutablepage_tags' is not a registered tag library. Must be one of:
[…]
```

Which occurs in `/home/cocolives/.virtualenvs/cocoliv.es/lib/python3.5/site-packages/puput/templates/puput/base.html`.

This makes me think templates must be updated too. I will do it manually on my test instance and report the changes here, but it seems templates are not updated in your PR.

regards,

**Comment by MiltonLn** [comment]
Hey @Karmak23, glad you found the issue, I was about to say that templatetags don't need to be updated at all. Please tell me if you found another issue. Thanks for the help!

**Comment by Karmak23** [comment]
Only the settings need to be updated. The template tags are OK, refering to the wagtail doc.
After that changes, everything runs.

I still have issues, like a 500 on the server when trying to browse pages in the admin, and a `FOREIGN KEY constraint error` when trying to delete a root page. But these could be consequences of a mess with other wagtail plugins (simple gallery, wagtail box) that I had before and wiped before upgrading to 2.0.

I'm too tired to continue now, but I will get another run to hunt these down tomorrow.

**Comment by sky-code** [comment]
When release?

**Comment by MiltonLn** [comment]
@marctc can you check the tests please?

**Comment by marctc** [comment]
I'm on it.

**Comment by marctc** [comment]
@MiltonLn replace `MIDDLEWARE_CLASSES` in settings.py with this:

```
MIDDLEWARE = (
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'wagtail.core.middleware.SiteMiddleware',
    'wagtail.contrib.redirects.middleware.RedirectMiddleware',
)
```

**Comment by MiltonLn** [comment]
Oh, I forgot. Done.

**Comment by marctc** [comment]
This page needs to be changed too: http://puput.readthedocs.io/en/latest/editors.html
* The image.
* The link needs to point to: http://docs.wagtail.io/en/v2.0/editor_manual/index.html

**Comment by MiltonLn** [comment]
Ok, updated the image and the link

**Comment by CptSupermrkt** [comment]
Heya, what's the official status of this, if I may ask?  This looks closed and committed, but "pip install puput" is still delving out 0.9.2.1 and subsequently downgrading Django, Wagtail, etc.

**Comment by marctc** [comment]
@CptSupermrkt I'm waiting to merge #154  in order to release a new version.

**Pull request merged**
