### PR TITLE
Made french translation

### PR DESCRIPTION
**Pull request by jojolalpin**

### CODE REVIEW

**Comment by marctc** [comment]
@jojolalpin notice that in this PR is included the changes that you made in `base.html`. The recomended way of creating a new PR is creating a new branch from master (getting the last changes). Can you fix it?

cheers!

**Comment by jojolalpin** [comment]
Hi Marc,

Yes I will do it asap
Sorry for the mistake.

Cheers

Le mar. 18 juil. 2017 15:28, Marc Tudurí <notifications@github.com> a
écrit :

**Comment by marctc** [comment]
Don't worry!!! I just told you for future PRs. Thanks!

**Comment by jojolalpin** [comment]
Do you want me to :
Remove last commit from PR ?
Create a new PR for translation only ?
Or just do things better next time ?

By the way, thanks for puput !

Le mar. 18 juil. 2017 15:33, Marc Tudurí <notifications@github.com> a
écrit :

**Comment by marctc** [comment]
> Create a new PR for translation only
This will be cleaner ;)

**Pull request closed without merging**
