### PR TITLE
Update MANIFEST.in

### PR DESCRIPTION
**Pull request by bashu**
excluded *.po from distribution

### CODE REVIEW

**Comment by marctc** [comment]
Hi @bashu. Since i've fixed the CI i relaunched the tests and it still failing. Can you check it please?
thanks!

**Comment by bashu** [comment]
@marctc sure!

**Comment by MiltonLn** [comment]
@marctc is this mergeable?

**Comment by MiltonLn** [comment]
@marctc closing it because it seems that we don't need it and it's stale, if you think this is wrong, please re-open

**Pull request closed without merging**
