### PR TITLE
Added insert custom JS codes via admin snippets

### PR DESCRIPTION
**Pull request by voylinux**
The idea is that the admin can insert custom JS codes such as analytics, piwik or any other tracking or custom JS code.

This option is secure because it is only available for admin users, not editors.
Also creates the option to activate or deactivate each code so you can for example activate or desactivate google experiments in analytics or other custom codes without need to hard-code JS in templates or creating new files only for temporal uses.

Think this can be helpful for blog administrators.

### CODE REVIEW

**Comment by marctc** [comment]
Hi @voylinux,
Thank you very much for this contribution. Maybe we can modify a little bit ;-). Instead of a Snippet, it would be better that CustomCode have a relation with BlogPage. With this, users with multiple blogs could put different js snippets depending on the blog page that they are editing.

**Comment by voylinux** [comment]
Sure, if you think the feature is useful let me change it and will send you a new pull request.
I am beginnig to understand how the structure in Wagtail works.

Let's close this one if you want and I will send you a new one with the correct changes.

Thanks.

**Comment by marctc** [comment]
Thank you Pablo!

**Comment by voylinux** [comment]
BTW ... Do you think this one would be better as an independent plugin even if we make it as you suggested?

**Comment by marctc** [comment]
I prefer that would be on the core. What do you think?

**Comment by voylinux** [comment]
I think so, but I am much less used than you do Django's modular philosophy.

**Pull request closed without merging**
