### PR TITLE
Allow serving by slug only

### LINKED ISSUE #32: Remove date from URL
I'd like to serve posts without the date in the URL. Something like:

```
    url(
        regex=r'^(?P<blog_slug>[-\w]+)/(?P<slug>[-\w]+)/$',
        view=EntryPageServe.as_view(),
        name='entry_age_serve_slug_only'
    )
```

I add this and adjust `EntryPageServe` and `BlogRoutes` etc but I keep getting a 404. 

~~What am I missing? How can I get the URL to serve the matching Entry?~~

Thanks.

### PR DESCRIPTION
**Pull request by carltongibson**
Fixes #32

### CODE REVIEW

**Comment by carltongibson** [comment]
I'm not sure if you want this but **not** having the date fragment in the URL is a common request for me.

**Comment by marctc** [comment]
As Puput is made as a Wagtail plugin so you can acces to a entry page with the url \<blog_slug\>/\<entry_slug\>, which is the default url routing method of Wagtail, besides \<blog_slug\>/\<year\>/\<month\>/\<day\>/\<entry_slug\>. However you have to replace the `href` content of all the entry links of the templates by `href="{% pageurl entry %}"` instead of the default templatetag `href="{% entry_url entry blog_page %}"`.

**Comment by carltongibson** [comment]
That means my changes aren't actually doing anything. Nice. 😃

**Comment by marctc** [comment]
Sorry for spending time on implementing this. Let me know if the solution that I gave you it works for you.

**Comment by carltongibson** [comment]
@marctc Not a problem. I'll have a play later and make sure I can do what I need without the changes. If so I'll close this (and #32)

**Comment by marctc** [comment]
:+1:

**Pull request closed without merging**
